/* QueueGo Market — shop-first storefront. Products are shown only after a shop is selected. */
(()=>{
'use strict';
let rows=[],marketShops=[],query='',category='all';
const h=v=>escapeHtml(String(v??''));
const available=r=>Math.max(0,Math.floor(Number(r.available_packs||0)));
function intoExistingCatalog(){
  const products=dbGet('qt_products',[]),byId=new Map(products.map(p=>[String(p.id),p]));
  for(const r of rows) byId.set(String(r.product_id),{...byId.get(String(r.product_id)),id:r.product_id,shopId:r.shop_user_id,shopProfileId:r.shop_id,name:r.name,category:r.category,description:r.description||'',image:r.image||'',price:Number(r.price),available:available(r)>0,marketUnit:r.unit,marketPackSize:Number(r.pack_size)});
  QT_DB_CACHE.qt_products=[...byId.values()];
}
function categoryLabel(v){return ({vegetable:'ผักสด',fruit:'ผลไม้',meat:'เนื้อสัตว์',fish:'อาหารทะเล',grocery:'ของชำ',market:'ตลาดสด'})[v]||'ตลาดสด'}
function shops(){const p=new Map();for(const r of rows){const id=String(r.shop_id||'');if(!id)continue;if(!p.has(id))p.set(id,{count:0,available:0,categories:new Set()});const x=p.get(id);x.count++;if(available(r)>0)x.available++;if(r.category)x.categories.add(r.category)}return marketShops.map(s=>{const x=p.get(String(s.shop_id))||{count:0,available:0,categories:new Set()};return{id:s.shop_id,userId:s.shop_user_id,name:s.shop_name||'ร้านตลาดสด',category:s.shop_category||'market',logo:s.shop_logo||'',cover:s.shop_cover||'',delivery:s.delivery_enabled!==false,count:x.count,available:x.available,categories:x.categories}})}
function shopCard(s){const tags=[categoryLabel(s.category),...[...s.categories].slice(0,2)].filter((x,i,a)=>x&&a.indexOf(x)===i).slice(0,3),photo=s.cover||s.logo;return `<button type="button" class="market-shop-card market-shop-card-rich" onclick="navigate('market-shop/${h(s.id)}')"><div class="market-shop-photo">${photo?`<img src="${h(photo)}" alt="${h(s.name)}" loading="lazy">`:'<span>🏪</span>'}<em>เปิด</em></div><div class="market-shop-detail"><h3>${h(s.name)}</h3><p class="market-shop-meta"><span>★ -</span><span>⌖ ใกล้คุณ</span><span>◷ 30–45 นาที</span></p><div class="market-tags">${tags.map(x=>`<span>${h(x)}</span>`).join('')}</div></div><div class="market-shop-side"><b>›</b></div></button>`}
function paintShops(){const box=document.getElementById('market-results');if(!box)return;const q=query.toLocaleLowerCase('th-TH');const list=shops().filter(s=>(category==='all'||s.category===category)&&(!q||(s.name+' '+s.category+' '+[...s.categories].join(' ')).toLocaleLowerCase('th-TH').includes(q)));box.innerHTML=list.length?list.map(shopCard).join(''):'<p class="market-empty">ยังไม่มีร้านตลาดสดที่ตรงกับการค้นหา</p>'}
window.qgMarketSearch=v=>{query=String(v||'').trim();paintShops()};
window.qgMarketCategory=v=>{category=v;document.querySelectorAll('.market-filter').forEach(b=>b.classList.toggle('active',b.dataset.cat===v));paintShops()};
window.qgMarketAdd=id=>{const r=rows.find(x=>String(x.product_id)===String(id));if(!r||!available(r))return toast('สินค้าหมด');intoExistingCatalog();addToCart(id);updateCartCountUI?.()};
window.renderMarket=function(){layout('ตลาดสด',`<section class="market-hero market-hero-photo" style="position:relative;overflow:hidden;min-height:220px;border-radius:18px;background:linear-gradient(135deg,#10271b 0%,#245b35 48%,#7b231f 100%);color:#fff"><div style="position:absolute;inset:0;background:radial-gradient(circle at 82% 34%,rgba(255,210,92,.32),transparent 28%),linear-gradient(90deg,rgba(0,0,0,.48),rgba(0,0,0,.08));"></div><div style="position:relative;z-index:1;padding:24px 20px;max-width:76%"><div style="display:inline-block;background:#e5202e;border-radius:999px;padding:7px 13px;font-weight:800;margin-bottom:10px">QueueGo Market</div><h1 style="margin:0 0 7px;font-size:32px;line-height:1.08;color:#fff">ตลาดสด <span style="color:#ff4653">ใกล้คุณ</span></h1><p style="margin:0 0 15px;font-weight:700;color:#fff">ของสดใหม่ ส่งถึงบ้านในพื้นที่</p><div style="display:flex;gap:8px;flex-wrap:wrap;font-size:12px;font-weight:700"><span style="background:#fff;color:#16864b;border-radius:999px;padding:7px 10px">🌿 ของสดใหม่</span><span style="background:#fff;color:#16864b;border-radius:999px;padding:7px 10px">◷ 30–45 นาที</span><span style="background:#fff;color:#16864b;border-radius:999px;padding:7px 10px">🚚 เริ่มต้น 30 บาท</span></div></div></section><label class="market-search"><span>ค้นหาร้านตลาดสด</span><input type="search" placeholder="ค้นหาชื่อร้าน เช่น ผักสด หมู ไก่ อาหารทะเล" oninput="qgMarketSearch(this.value)"></label><div class="market-filters"><button class="market-filter active" data-cat="all" onclick="qgMarketCategory('all')">▣ ทั้งหมด</button><button class="market-filter" data-cat="vegetable" onclick="qgMarketCategory('vegetable')">🌿 ผักสด</button><button class="market-filter" data-cat="fruit" onclick="qgMarketCategory('fruit')">🍎 ผลไม้</button><button class="market-filter" data-cat="meat" onclick="qgMarketCategory('meat')">🥩 เนื้อสัตว์</button><button class="market-filter" data-cat="fish" onclick="qgMarketCategory('fish')">🐟 อาหารทะเล</button></div><div class="market-heading-row"><h2 class="market-heading">ร้านค้า</h2><span>⌖ ใกล้คุณที่สุด⌄</span></div><div id="market-results" class="market-shop-list"><p>กำลังโหลดร้านตลาดสด...</p></div>`);Promise.all([qtSupabaseTable('rpc/market_public_shops',{method:'POST',body:{}}),qtSupabaseTable('rpc/market_public_catalog',{method:'POST',body:{}}).catch(()=>[])]).then(([sd,pd])=>{if(!document.getElementById('market-results'))return;marketShops=Array.isArray(sd)?sd:[];rows=Array.isArray(pd)?pd:[];intoExistingCatalog();paintShops()}).catch(err=>{const box=document.getElementById('market-results');if(box)box.textContent='โหลดร้านไม่สำเร็จ: '+(err.message||err)})};
window.renderMarketShop=function(id){
  const render=()=>{
    const list=rows.filter(r=>String(r.shop_id)===String(id)),first=list[0];
    if(!first){layout('ตลาดสด','<button class="btn-secondary" onclick="navigate(\'market\')">← กลับตลาดสด</button><p class="market-empty">ไม่พบร้านนี้หรือร้านยังไม่มีสินค้าพร้อมขาย</p>');return;}
    intoExistingCatalog();
    layout(first.shop_name||'ร้านตลาดสด',`<section class="market-shop-head"><button type="button" class="btn-secondary" onclick="navigate('market')">← ร้านตลาดสด</button><div>${first.shop_logo?`<img src="${h(first.shop_logo)}" alt="">`:'<span>🏪</span>'}<div><small>QueueGo Market</small><h1>${h(first.shop_name)}</h1><p>เลือกสินค้าจากร้านนี้</p></div></div></section><div class="market-list">${list.map(r=>`<article class="market-card"><div class="market-photo">${r.image?`<img src="${h(r.image)}" alt="${h(r.name)}" loading="lazy">`:'🛒'}</div><div class="market-detail"><small>${h(r.category)}</small><h3>${h(r.name)}</h3><p>${Number(r.pack_size)} ${h(r.unit)} / ชุด · เหลือ ${available(r)} ชุด</p><div><b>${Number(r.price).toLocaleString('th-TH')} ฿</b><button type="button" ${available(r)?'':'disabled'} onclick="qgMarketAdd('${h(r.product_id)}')">${available(r)?'เพิ่มสินค้า':'หมด'}</button></div></div></article>`).join('')}</div>`);
  };
  if(rows.length)return render();
  qtSupabaseTable('rpc/market_public_catalog',{method:'POST',body:{}}).then(data=>{rows=Array.isArray(data)?data:[];render()}).catch(err=>layout('ตลาดสด','<p class="market-empty">โหลดร้านไม่สำเร็จ: '+h(err.message||err)+'</p>'));
};
const route=window.qtRouteRender;window.qtRouteRender=function(){
  const parts=location.hash.replace('#','').split('/'),page=parts[0];
  if(page==='market'||page==='market-shop'){const u=currentUser();if(u&&u.type!=='customer')return renderQueueGoRoleNotice(u);return page==='market'?renderMarket():renderMarketShop(parts[1])}
  return route();
};
const home=window.renderHome;window.renderHome=function(){home();const target=document.getElementById('qg-categories');if(target&&!target.querySelector('.market-home-link')){const b=document.createElement('button');b.type='button';b.className='qg-cat market-home-link';b.innerHTML='<span class="qg-cat-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 9h18l-2 11H5L3 9Z"/><path d="m7 9 5-6 5 6M9 13v4m6-4v4"/></svg></span><b>ตลาดสด</b>';b.setAttribute('aria-label','ตลาดสด QueueGo');b.onclick=()=>navigate('market');target.append(b)}};
})();