(()=>{'use strict';
 const base='https://pkypiqhlrmzocysgeqew.supabase.co/rest/v1/rpc/';
 const key='sb_publishable_Vn2Il4jp-iBtzNsGRNY8Lg_Tpvk2Vre';
 const storage='queuego-table-session-v1',pendingKey='queuego-table-pending-v1';
 const app=document.querySelector('#app');let session=null,device=null,products=[],cart=new Map(),pending=null,submitting=false;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&quot;'}[c]));
 const money=x=>Number(x).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2})+' ฿';
 async function rpc(name,body){const r=await fetch(base+name,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.message||'เชื่อมต่อเซิร์ฟเวอร์ไม่สำเร็จ');return d}
 function locationPoint(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('อุปกรณ์นี้ไม่มีระบบตำแหน่งที่ตั้ง'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),e=>reject(Error('กรุณาเปิดสิทธิ์ตำแหน่งที่ตั้งและอยู่ภายใน 100 เมตรจากร้าน ('+e.message+')')),{enableHighAccuracy:true,maximumAge:0,timeout:15000})})}
 function save(){localStorage.setItem(storage,JSON.stringify({session:session.session_id,device}))}
 function expired(){app.innerHTML='<header><b><i>Q</i> QueueGo</b></header><section class="card"><h1>สิทธิ์การสั่งอาหารจากโต๊ะนี้หมดอายุแล้ว</h1><p>กรุณาสแกน QR Code ที่โต๊ะอีกครั้ง</p></section>';localStorage.removeItem(storage);localStorage.removeItem(pendingKey)}
 function error(e){app.innerHTML='<header><b><i>Q</i> QueueGo</b></header><section class="card"><h1>ยังเปิดโต๊ะไม่ได้</h1><p class="banner">'+esc(e.message||e)+'</p><button class="primary" onclick="location.reload()">ลองอีกครั้ง</button></section>'}
 async function status(){session=await rpc('qg_table_session_status',{p_session:session.session_id,p_device_key:device});if(!session.active){expired();return false}return true}
 async function init(){try{const hash=location.hash.slice(1),token=hash.startsWith('scan/')?hash.slice(5):null;
 if(token){device=crypto.randomUUID();const point=await locationPoint();session=await rpc('qg_table_scan',{p_qr_token:token,p_device_key:device,p_lat:point.lat,p_lng:point.lng});save();history.replaceState(null,'',location.pathname+'#table-order')}
 else{const saved=JSON.parse(localStorage.getItem(storage)||'null');if(!saved){expired();return}device=saved.device;session={session_id:saved.session};if(!await status())return}
 products=await rpc('qg_table_catalog',{p_session:session.session_id,p_device_key:device});const savedPending=JSON.parse(localStorage.getItem(pendingKey)||'null');pending=savedPending?.session===session.session_id?savedPending:null;render();
 }catch(e){error(e)}}
 function render(){const all=[...cart.entries()].map(([id,v])=>({...v,id}));const total=all.reduce((s,c)=>s+c.quantity*Number(products.find(p=>p.id===c.id)?.price||0),0);
 app.innerHTML=`<header><b><i>Q</i> QueueGo</b><span>${esc(session.table_name)}</span></header><section class="card"><h1>${esc(session.shop_name)}</h1><p>สั่งอาหารจากโต๊ะ · ส่งเข้าครัวทันที</p><small class="muted">ใช้ได้ถึง ${new Date(session.expires_at).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})} ตามเวลาของเซิร์ฟเวอร์</small></section><section class="card"><h2>เมนูอาหาร</h2><div class="products">${products.map(p=>`<div class="product">${p.image?`<img loading="lazy" src="${esc(p.image)}" alt="">`:''}<div class="text"><b>${esc(p.name)}</b><small>${esc(p.description||'')} · ${money(p.price)}</small></div><button data-add="${p.id}" aria-label="เพิ่ม ${esc(p.name)}">＋</button></div>`).join('')||'<p>ร้านยังไม่มีเมนูหน้าร้าน</p>'}</div></section><section class="card"><h2>รายการที่เลือก</h2>${all.map(c=>{const p=products.find(x=>x.id===c.id);return `<div class="cart"><div class="cart-row"><b>${esc(p?.name)} · ${money(p?.price)}</b><button data-minus="${c.id}">−</button><strong>${c.quantity}</strong><button data-add="${c.id}">＋</button></div><input data-note="${c.id}" maxlength="500" placeholder="หมายเหตุสำหรับครัว" value="${esc(c.note||'')}"></div>`}).join('')||'<p>แตะ ＋ ที่เมนูเพื่อเริ่มสั่ง</p>'}</section><div id="feedback" role="status"></div><div class="footer"><button class="primary" id="submit" ${!all.length||submitting?'disabled':''}>${pending?'ตรวจออเดอร์ที่ส่งไปแล้ว':'ส่งเข้าครัว · '+money(total)}</button><small>ออเดอร์หน้าร้าน ไม่มีค่า GP และค่าส่ง</small></div>`;
 app.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{if(pending)return notice('กำลังตรวจออเดอร์ก่อนหน้า');const id=b.dataset.add,c=cart.get(id)||{quantity:0,note:''};c.quantity++;cart.set(id,c);render()});
 app.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{if(pending)return notice('กำลังตรวจออเดอร์ก่อนหน้า');const id=b.dataset.minus,c=cart.get(id);if(--c.quantity<=0)cart.delete(id);render()});
 app.querySelectorAll('[data-note]').forEach(b=>b.onchange=()=>{if(pending)return;const c=cart.get(b.dataset.note);if(c)c.note=b.value.trim()});app.querySelector('#submit').onclick=submit}
 function notice(s){const f=app.querySelector('#feedback');if(f)f.innerHTML='<p class="banner">'+esc(s)+'</p>'}
 async function submit(){if(submitting)return;if(!pending){const items=[...cart.entries()].map(([id,v])=>({id,quantity:v.quantity,note:v.note||''})).sort((a,b)=>a.id.localeCompare(b.id));if(!items.length)return;pending={session:session.session_id,request:crypto.randomUUID(),items};localStorage.setItem(pendingKey,JSON.stringify(pending))}
 submitting=true;render();try{if(!await status())return;const point=await locationPoint();const result=await rpc('qg_table_checkout',{p_session:session.session_id,p_device_key:device,p_request:pending.request,p_items:pending.items,p_lat:point.lat,p_lng:point.lng});cart.clear();pending=null;localStorage.removeItem(pendingKey);render();const f=app.querySelector('#feedback');if(f)f.innerHTML='<p class="good">ส่งเข้าครัวแล้ว · เลขออเดอร์ '+esc(result.order_id)+' คุณสั่งอาหารเพิ่มได้ในเวลาที่เหลือ</p>';window.scrollTo({top:0,behavior:'smooth'})
 }catch(e){notice(e.message+' · กดตรวจออเดอร์เดิมอีกครั้ง')}finally{submitting=false;const b=app.querySelector('#submit');if(b)b.disabled=false}}
 init();
})();
