const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert'),{JSDOM}=require('jsdom');
(async()=>{let checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++};const d=new JSDOM(fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8'),{url:'https://queuego.test/#login',runScripts:'outside-only'}),w=d.window,ctx=d.getInternalVMContext();w.AbortSignal=AbortSignal;w.fetch=async()=>({ok:true,json:async()=>[]});w.setTimeout=()=>0;w.scrollTo=()=>{};w.crypto.randomUUID=()=>crypto.randomUUID();for(const s of w.document.querySelectorAll('script'))if(!s.src&&s.textContent.trim())vm.runInContext(s.textContent,ctx);const run=s=>vm.runInContext(s,ctx);
run("window.loginFixture={id:'customer',auth_user_id:'auth-customer',role:'customer',status:'active',name:'Customer'};auth=async()=>({access_token:'fixture',refresh_token:'refresh',user:{id:'auth-customer',user_metadata:{role:'admin'}}});db=async()=>[loginFixture];");await run("login('customer@example.test','fixture')");eq(run('S.get().userId'),'customer');
for(const fixture of [null,{id:'shop',role:'shop',status:'active'},{id:'customer',role:'customer',status:'suspended'}]){w.loginFixture=fixture;run("S.clear();db=async()=>loginFixture?[loginFixture]:[]");await assert.rejects(run("login('fixture@example.test','fixture')"));eq(run('S.get()'),null)}
// Use actual session refresh function, not an Auth API response, to verify stale completion cannot restore logout.
const source=fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8');const tokenSource=source.slice(source.indexOf('async function token('),source.indexOf('const emailOf='));run(tokenSource);run("S.set({userId:'customer',authUserId:'auth-customer',accessToken:'old',refreshToken:'old-refresh',expiresAt:1});auth=()=>new Promise(resolve=>window.resolveRefresh=resolve)");const refreshing=run('token()');run('S.clear()');w.resolveRefresh({access_token:'new',refresh_token:'new-refresh'});eq(await refreshing,'');eq(run('S.get()'),null);
run("S.set({userId:'customer',authUserId:'auth-customer',accessToken:'old',refreshToken:'old-refresh',expiresAt:1});auth=()=>new Promise(resolve=>window.resolveRefresh=resolve)");const stale=run('token()');run("S.set({userId:'other',authUserId:'auth-other',accessToken:'other-token',refreshToken:'other-refresh'})");w.resolveRefresh({access_token:'new',refresh_token:'new-refresh'});eq(await stale,'');eq(run('S.get().accessToken'),'other-token');
const setup="layout=()=>{};token=async()=>S.get()?.accessToken||'';S.set({userId:'customer',authUserId:'auth-customer',accessToken:'customer-token'});currentPos={lat:13,lng:100,address:'Address'};cart={shopId:'shop',items:[{id:'product',name:'Food',price:100,qty:1}]};saveCart();window.__checkoutPickedLocation=()=>currentPos;document.getElementById('root').innerHTML='<textarea id=\"delivery-address\">Address</textarea><button id=\"place-order-btn\"></button>';window.calls=[];window.gate=null;db=async(path,opts)=>{calls.push({path,opts});if(path.startsWith('orders?')){await gate;return []}if(path.startsWith('shop_profiles?'))return [{id:'shop',latitude:13,longitude:100}];return {id:opts.body.p_order_id}};";
run(setup+"gate=new Promise(resolve=>window.resolveRead=resolve)");const pending=run('placeOrder()');run("S.set({userId:'other',authUserId:'auth-other',accessToken:'other-token'});cart={shopId:'other-shop',items:[{id:'other-product',price:200,qty:2}]};saveCart()");w.resolveRead();await pending;eq(run("calls.some(x=>x.path==='rpc/queuego_place_cash_order')"),false);eq(run('cart.shopId'),'other-shop');eq(run('checkoutBusy'),false);
run(setup+"db=async(path,opts)=>{calls.push({path,opts});if(path.startsWith('orders?'))return [];if(path.startsWith('shop_profiles?'))return [{id:'shop',latitude:13,longitude:100}];await new Promise(resolve=>window.resolveOrder=()=>resolve({id:opts.body.p_order_id}));return {id:opts.body.p_order_id}};");const order=run('placeOrder()');for(let i=0;i<8;i++)await Promise.resolve();eq(typeof w.resolveOrder,'function');eq(run("calls.find(x=>x.path==='rpc/queuego_place_cash_order').opts.token"),'customer-token');run("S.set({userId:'other',authUserId:'auth-other',accessToken:'other-token'});cart={shopId:'other-shop',items:[{id:'other-product',price:200,qty:2}]};saveCart();localStorage.setItem('qg_pending_checkout_other','keep')");w.resolveOrder();await order;eq(run('cart.shopId'),'other-shop');eq(w.localStorage.getItem('qg_pending_checkout_other'),'keep');eq(w.localStorage.getItem('qg_pending_checkout_customer'),null);eq(JSON.parse(w.localStorage.getItem('qt_cart_customer')).items.length,0);d.window.close();console.log(JSON.stringify({checks,failures:0,scope:'isolated authoritative Customer login and session/checkout ownership races; no live Auth account test'}));})().catch(e=>{console.error(e);process.exit(1)});
