const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{let checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++};
function boot(){const d=new JSDOM('<div id="app"></div>',{url:'https://queuego.test/merchant/#pos',runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;w.toast=()=>{};w.qtSessionRead=()=>({authUserId:'actor',accessToken:'token'});w.qtGetAccessToken=async()=>'token';w.crypto.randomUUID=()=>crypto.randomUUID();w.QT_SUPABASE_CONFIG={URL:'https://test.invalid',KEY:'fixture'};w.AbortSignal=AbortSignal;return {d,w,eval:file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),d.getInternalVMContext())}}
const p=boot();let calls=[],written=[],unblock,hold=true;p.w.localStorage.setItem('qg_printer_settings_v1',JSON.stringify({autoKitchen:true,autoReceipt:true}));
p.w.open=()=>({document:{write:s=>written.push(s),close:()=>{}}});
const bills={one:{id:'one',shop_id:'shop',order_number:'ONE',order_type:'TAKEAWAY',created_at:new Date().toISOString()},two:{id:'two',shop_id:'shop',order_number:'TWO',order_type:'TAKEAWAY',created_at:new Date().toISOString()}};let batch=1;
p.w.qtSupabaseTable=async q=>{calls.push(q);if(q.startsWith('orders?')){if(hold){hold=false;await new Promise(r=>unblock=r)}return [bills[q.includes('id=eq.one')?'one':'two']]}return [{item_name:'old item',quantity:1,pos_batch:0},{item_name:'batch '+batch,quantity:1,pos_batch:batch}]};
p.eval('merchant/printer-v1.js');eq(p.w.document.querySelector('#qg-printer-btn'),null);p.w.qgPrinterMount('shop','Shop');eq(p.w.document.querySelectorAll('#qg-printer-btn').length,1);
p.w.qgPrinterOrderChanged({new:{...bills.one,kitchen_status:'SENT_TO_KITCHEN'}});p.w.qgPrinterOrderChanged({new:{...bills.two,kitchen_status:'SENT_TO_KITCHEN'}});p.w.qgPrinterOrderChanged({new:{...bills.one,kitchen_status:'SENT_TO_KITCHEN'}});await tick();eq(written.length,0);unblock();for(let i=0;i<10;i++)await tick();eq(written.length,2);eq(written[0].includes('old item'),false);eq(written[0].includes('batch 1'),true);
batch=2;p.w.qgPrinterOrderChanged({new:{...bills.one,kitchen_status:'SENT_TO_KITCHEN'}});for(let i=0;i<10;i++)await tick();eq(written.length,3);eq(written[2].includes('batch 2'),true);
p.w.qgPrinterOrderChanged({new:{...bills.two,payment_status:'PAID'}});for(let i=0;i<10;i++)await tick();eq(written.length,4);eq(written[3].includes('old item'),true);
hold=true;p.w.qgPrinterOrderChanged({new:{...bills.two,kitchen_status:'SENT_TO_KITCHEN'}});await tick();p.w.qgPrinterDisconnect();p.w.qgPrinterMount('other','Other');unblock();for(let i=0;i<10;i++)await tick();eq(written.length,4);eq(p.w.document.querySelectorAll('#qg-printer-btn').length,1);p.w.qgPrinterDisconnect();eq(p.w.document.querySelector('#qg-printer-btn'),null);eq(calls.some(q=>q.startsWith('rpc/pos_my_shop')),false);p.d.window.close();
const t=boot();let requests=[],channels=[],removed=0,gate=null,shopCalls=0,authCalls=[],staffFixture={user_id:'staff',shop_id:'shop',display_name:'Staff',staff_role:'WAITER',active:true,permissions:{}};
t.w.qtSupabaseTable=async(q,opts)=>{requests.push(q);if(q.startsWith('pos_staff?'))return [staffFixture];if(q==='rpc/pos_set_staff_role'){staffFixture.staff_role=opts.body.p_role;return null}if(q==='rpc/pos_my_shop'){shopCalls++;if(gate)await gate;return 'shop'}if(q==='rpc/pos_is_owner')return true;if(q.startsWith('shop_profiles?'))return [{shop_name:'Shop'}];if(q.includes('status=in.'))return [{id:'pending',status:'pending',order_number:'P'},{id:'search',status:'searching_rider',order_number:'S'},{id:'assigned',status:'rider_assigned',rider_id:'rider',order_number:'A'}];return []};
t.w.supabase={createClient:()=>({realtime:{setAuth:async token=>{authCalls.push(token)}},removeAllChannels:async()=>{},removeChannel:async()=>{removed++},channel:()=>{const c={events:[],on(...a){this.events.push(a);return this},subscribe(cb){this.cb=cb;return this}};channels.push(c);return c}})};
t.eval('merchant/pos-table-v2.js');t.w.qgPosRoute();await Promise.all([t.w.qgPosReload(),t.w.qgPosReload()]);for(let i=0;i<5;i++)await tick();eq(shopCalls,1);eq(channels.length,1);eq(channels[0].events.filter(e=>e[1].table==='orders').length,1);eq(requests.some(q=>q.includes('searching_rider,rider_assigned')),true);
const initialAuthCalls=authCalls.length;t.w.qtGetAccessToken=async()=>'refreshed-token';await t.w.qgPosReload();for(let i=0;i<5;i++)await tick();eq(channels.length,1);eq(authCalls.length,initialAuthCalls+1);eq(authCalls.at(-1),'refreshed-token');
const staffReads=requests.filter(q=>q.startsWith('pos_staff?')).length;t.w.qgPosView('staff');eq(t.w.document.getElementById('qg-pos-staff-list').textContent.includes('Staff · WAITER'),true);eq(requests.filter(q=>q.startsWith('pos_staff?')).length,staffReads);t.w.prompt=()=> 'CASHIER';t.w.confirm=()=>true;await t.w.qgPosStaffEdit('staff');eq(requests.filter(q=>q.includes('pos_staff?')&&q.includes('user_id=eq.')).length,0);eq(staffFixture.staff_role,'CASHIER');eq(t.w.document.getElementById('qg-pos-staff-list').textContent.includes('CASHIER'),true);const writesBefore=requests.filter(q=>q==='rpc/pos_set_staff_role').length;await t.w.qgPosStaffEdit('foreign');eq(requests.filter(q=>q==='rpc/pos_set_staff_role').length,writesBefore);
t.w.qgPosView('kitchen');const html=t.w.document.getElementById('app').innerHTML;eq(html.includes("qgPosDeliveryAction('assigned','preparing')"),true);eq(html.includes("qgPosDeliveryAction('search'"),false);eq(html.includes('กำลังหาไรเดอร์'),true);
// A retired socket must not keep refreshing or prevent one scoped reconnect.
const timers=new Map();let timerId=0;t.w.setTimeout=(fn,delay)=>{const id=++timerId;timers.set(id,{fn,delay});return id};t.w.clearTimeout=id=>timers.delete(id);
channels[0].cb('CLOSED');eq(removed,1);eq(timers.size,1);eq([...timers.values()][0].delay,15000);channels[0].cb('CHANNEL_ERROR');eq(timers.size,1);const retiredCalls=shopCalls;channels[0].events[0][2]({new:{id:'retired'}});await tick();eq(shopCalls,retiredCalls);
const timer=[...timers.values()][0];timers.clear();timer.fn();for(let i=0;i<8;i++)await tick();eq(channels.length,2);eq(shopCalls,retiredCalls+1);channels[0].cb('SUBSCRIBED');await tick();eq(shopCalls,retiredCalls+1);channels[1].cb('CHANNEL_ERROR');eq(removed,2);eq(timers.size,1);await t.w.qgPosReload();for(let i=0;i<5;i++)await tick();eq(channels.length,3);channels[2].cb('SUBSCRIBED');for(let i=0;i<5;i++)await tick();eq(timers.size,0);
let resolve;gate=new Promise(r=>resolve=r);const before=shopCalls;channels[2].events[0][2]({new:{id:'pending'}});channels[2].events[0][2]({new:{id:'pending'}});await tick();eq(shopCalls,before+1);t.w.location.hash='#dashboard';t.w.qgPosDisconnect();t.w.document.getElementById('app').innerHTML='dashboard';resolve();for(let i=0;i<10;i++)await tick();eq(t.w.document.getElementById('app').innerHTML,'dashboard');eq(channels.length,3);eq(removed,3);eq(timers.size,0);t.d.window.close();
// An SDK download that never finishes must release its script/task and allow recovery.
const sdk=boot(),sdkTimers=new Map();let sdkId=0;sdk.w.setTimeout=(fn,delay)=>{const id=++sdkId;sdkTimers.set(id,{fn,delay});return id};sdk.w.clearTimeout=id=>sdkTimers.delete(id);sdk.w.qtSupabaseTable=t.w.qtSupabaseTable;sdk.eval('merchant/pos-table-v2.js');sdk.w.qgPosRoute();for(let i=0;i<8;i++)await tick();eq(sdk.w.document.querySelectorAll('script').length,1);const timeout=[...sdkTimers.entries()].find(([,v])=>v.delay===10000);eq(!!timeout,true);sdkTimers.delete(timeout[0]);timeout[1].fn();for(let i=0;i<5;i++)await tick();eq(sdk.w.document.querySelectorAll('script').length,0);eq([...sdkTimers.values()].filter(v=>v.delay===15000).length,1);sdk.w.qgPosDisconnect();eq(sdkTimers.size,0);sdk.w.location.hash='#pos';sdk.w.qgPosRoute();for(let i=0;i<8;i++)await tick();eq(sdk.w.document.querySelectorAll('script').length,1);eq([...sdkTimers.values()].filter(v=>v.delay===10000).length,1);sdk.w.qgPosDisconnect();for(let i=0;i<5;i++)await tick();eq(sdk.w.document.querySelectorAll('script').length,0);eq(sdkTimers.size,0);sdk.d.window.close();
console.log(JSON.stringify({checks,failures:0,scope:'isolated POS lifecycle and printer queue; physical printers/realtime server not certified'}));})().catch(e=>{console.error(e);process.exit(1)});
