const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const source=fs.readFileSync(path.resolve(__dirname,'../rider/index.html'),'utf8');
let checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++};const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}};const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve()};
(async()=>{
 let now=100000,requests=[],gate=null,serial=0;const timers=new Map(),removed=[],added=[],badge={style:{}},label={textContent:''};const map={location(){},zoom(){},Overlays:{add:x=>added.push(x),remove:x=>removed.push(x),clear(){}},pause(){},placeholder:()=>({remove(){}})};
 const session={authUserId:'a',sessionId:'sa'},S={user:{id:'rider'},session,map,pos:{lat:13,lng:100},activeOrder:{id:'o',status:'assigned',pickup_latitude:13.1,pickup_longitude:100.1,delivery_latitude:13.2,delivery_longitude:100.2},routeOverlays:[],jobMarkers:[]};
 const geo={features:[{properties:{distance:1200,interval:240},geometry:{type:'LineString',coordinates:[[100,13],[100.1,13.1]]}}]};
 const ctx=vm.createContext({S,Date:class extends Date{static now(){return now}},Promise,AbortController,Number,String,JSON,encodeURIComponent,document:{hidden:false,getElementById:id=>id==='route-badge'?badge:label},navigator:{onLine:true},riderSessionMatches:s=>s===S.session,statusFromRow:o=>o.status,haversineKm:(a,b,c,d)=>Math.hypot(a-c,b-d)*111,setTimeout:f=>{timers.set(++serial,f);return serial},clearTimeout:id=>timers.delete(id),fetch:async(url,opts)=>{requests.push({url,opts});if(gate)return gate.promise;return {ok:true,json:async()=>geo}},longdo:{Polyline:function(points,style){this.points=points;this.style=style}}});
 vm.runInContext(source.slice(source.indexOf('const LONGDO_API_KEY='),source.indexOf('function initMap()')),ctx);
 vm.runInContext(source.slice(source.indexOf('function qgRemoveOverlay('),source.indexOf('/* ---------- sheet')),ctx);const run=s=>vm.runInContext(s,ctx);
 gate=deferred();const first=run('drawActiveRoute()');for(let i=0;i<20;i++)run('drawActiveRoute()');eq(requests.length,1);eq(new URL(requests[0].url).searchParams.get('tlat'),'13.1');gate.resolve({ok:true,json:async()=>geo});gate=null;await first;eq(added.length,1);eq(label.textContent,'ไปร้าน • 1.2 กม. • 4 นาที');eq(timers.size,0);
 for(let i=0;i<20;i++)await run('drawActiveRoute()');eq(requests.length,1);now+=15000;S.pos={lat:13.001,lng:100};await run('drawActiveRoute()');eq(requests.length,2);eq(removed.length,1);
 // Changing pickup to delivery invalidates the old request immediately.
 now+=15000;S.pos={lat:13.002,lng:100};gate=deferred();const old=run('drawActiveRoute()');const oldSignal=requests.at(-1).opts.signal;S.activeOrder.status='in_progress';const oldGate=gate;gate=null;await run('drawActiveRoute()');eq(oldSignal.aborted,true);eq(new URL(requests.at(-1).url).searchParams.get('tlat'),'13.2');const count=added.length;oldGate.resolve({ok:true,json:async()=>geo});await old;eq(added.length,count);eq(label.textContent.startsWith('ไปหาลูกค้า'),true);
 // A newly received unclaimed offer immediately routes and focuses the map on its pickup.
 S.activeOrder=null;S.openJobs=[{order:{id:'offer',status:'searching_rider',pickup_latitude:14,pickup_longitude:101,delivery_latitude:14.5,delivery_longitude:101.5}}];S.pos={lat:13,lng:100};const mapViews=[];map.location=(p)=>mapViews.push({type:'location',p});map.zoom=(z)=>mapViews.push({type:'zoom',z});
 await run('drawActiveRoute()');eq(new URL(requests.at(-1).url).searchParams.get('tlat'),'14');eq(label.textContent.startsWith('ไปร้าน'),true);eq(mapViews.at(-2).p.lat,13.5);eq(mapViews.at(-1).z,11);
 S.openJobs=[];S.activeOrder={id:'o',status:'assigned',pickup_latitude:13.1,pickup_longitude:100.1,delivery_latitude:13.2,delivery_longitude:100.2};
 // Completing a job while the provider is pending cannot redraw its route.
 now+=15000;S.pos={lat:13.003,lng:100};gate=deferred();const retiring=run('drawActiveRoute()');const retiredSignal=requests.at(-1).opts.signal;S.activeOrder=null;await run('drawActiveRoute()');eq(retiredSignal.aborted,true);gate.resolve({ok:true,json:async()=>geo});gate=null;await retiring;eq(S.routeOverlays.length,0);eq(badge.style.display,'none');
 // Failed routing is explicitly an error, never a fabricated straight-line route.
 S.activeOrder={id:'new',status:'assigned',pickup_latitude:14,pickup_longitude:101};ctx.fetch=async()=>({ok:true,json:async()=>({features:[]})});await run('drawActiveRoute()');eq(label.textContent.includes('โหลดเส้นทางไม่สำเร็จ'),true);eq(S.routeOverlays.length,0);
 // Provider timeout releases the request so the next attempt can recover.
 ctx.fetch=async(_u,{signal})=>new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(Error('timeout')),{once:true}));const timeout=run('drawActiveRoute()');for(const f of [...timers.values()])f();await timeout;eq(timers.size,0);ctx.fetch=async()=>({ok:true,json:async()=>geo});await run('drawActiveRoute()');eq(S.routeOverlays.length,1);
 // Invalid/missing coordinates never become a route to (0,0).
 S.activeOrder.pickup_latitude=null;await run('drawActiveRoute()');eq(S.routeOverlays.length,0);eq(run('validRiderCoordinate(null,100)'),false);
 // GPS callbacks are owned by a single live watcher, including watch ID zero.
 const watches=[],cleared=[];let renders=0;ctx.navigator.geolocation={watchPosition:(ok,error)=>{watches.push({ok,error});return watches.length-1},clearWatch:id=>cleared.push(id)};ctx.toast=()=>{};ctx.placeRiderMarker=()=>renders++;ctx.renderSheet=()=>{};ctx.pushLocation=()=>{};S.online=false;
 vm.runInContext(source.slice(source.indexOf('function startGeolocation()'),source.indexOf('function recenterMap()')),ctx);
 run('startGeolocation();startGeolocation()');eq(cleared[0],0);watches[0].ok({coords:{latitude:15,longitude:102}});eq(renders,0);watches[1].ok({coords:{latitude:15,longitude:102}});eq(renders,1);run('disposeRiderMap()');watches[1].ok({coords:{latitude:16,longitude:103}});eq(renders,1);eq(S.pos,null);eq(S.map,null);
 // Position uploads use the captured account and coalesce a GPS burst to the latest position.
 vm.runInContext(source.slice(source.indexOf('let riderLocationWrite='),source.indexOf('let riderRefreshTask=')),ctx);
 S.user={id:'rider'};S.session=session;S.riderProfile={id:'profile'};S.pos={lat:13,lng:100};S.online=true;const writes=[];let tokenGate=deferred();ctx.getAccessToken=()=>tokenGate.promise;ctx.sbTable=async(path,opts)=>{writes.push({path,opts});return []};
 const stale=run('pushLocation()');S.session={authUserId:'b',sessionId:'sb'};S.user={id:'other'};tokenGate.resolve('old-token');await stale;eq(writes.length,0);
 S.session=session;S.user={id:'rider'};ctx.getAccessToken=async()=>'fixture';const writeGate=deferred();ctx.sbTable=async(path,opts)=>{writes.push({path,opts});if(writes.length===1)await writeGate.promise;return []};const burst=run('pushLocation()');await flush();for(let i=0;i<20;i++){S.pos={lat:13+i/100,lng:100};run('pushLocation()')}eq(writes.length,1);writeGate.resolve();await burst;eq(writes.length,2);eq(writes[1].opts.body.latitude,13.19);eq(writes[1].path,'rider_profiles?user_id=eq.rider');
 console.log(JSON.stringify({checks,failures:0,scope:'isolated Longdo route coalescing, caching, cancellation, timeout and GPS ownership; live routing and physical GPS not certified'}));
})().catch(e=>{console.error(e);process.exit(1)});
