/* Admin Market vehicle approval and order trace; read and write via authenticated RLS/RPC. */
(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const admin=()=>currentUser()?.type==='admin'&&currentUser()?.status==='approved';
async function api(path){return qtSupabaseTable(path,{accessToken:await qtGetAccessToken()})}
window.renderAdminMarket=async()=>{if(!admin())return navigate('login');layout('ตลาดสด',`<section class="card qg-admin-market"><button onclick="navigate('admin')">‹ ศูนย์ควบคุม</button><h1>ตลาดสดและรถรับงาน</h1><p>ความจุรถที่ผ่านการตรวจสอบจะถูกบังคับตอนแสดงงานและกดรับงาน</p><div id="qg-market-admin">กำลังโหลดข้อมูลจริง...</div></section>`);const el=document.getElementById('qg-market-admin');try{const [riders,orders]=await Promise.all([api('rider_profiles?select=id,rider_name,vehicle_type,vehicle_plate,vehicle_status,vehicle_capacity_kg,vehicle_verified_at,status,metadata&status=eq.active&order=created_at.desc&limit=100'),api('orders?select=id,order_number,status,fulfillment_vertical,subtotal,total_amount,created_at&fulfillment_vertical=in.(market,grocery)&order=created_at.desc&limit=50')]);if(!el.isConnected)return;el.innerHTML=`<h2>รถและความจุ</h2>${(riders||[]).map(r=>`<article><b>${esc(r.rider_name||'ไรเดอร์')}</b> · ${esc(r.vehicle_type)} · ${esc(r.vehicle_plate||'')}<br><small>สถานะ ${esc(r.vehicle_status)} · ยืนยัน ${Number(r.vehicle_capacity_kg||0)} กก. · ขอ ${esc(r.metadata?.requestedCapacityKg||'-')} กก.</small><div><button onclick="qgAdminVehicle('${r.id}','active',${Number(r.vehicle_capacity_kg||r.metadata?.requestedCapacityKg||20)})">ตรวจและอนุมัติความจุ</button><button onclick="qgAdminVehicle('${r.id}','suspended',0)">ระงับรถ</button></div></article>`).join('')||'<p>ยังไม่มีไรเดอร์ที่เปิดใช้งาน</p>'}<h2>ออเดอร์ตลาดล่าสุด</h2>${(orders||[]).map(o=>`<article><b>${esc(o.order_number||o.id)}</b> · ${esc(o.fulfillment_vertical)} · ${esc(o.status)} · ${Number(o.total_amount||0).toLocaleString('th-TH')} ฿</article>`).join('')||'<p>ยังไม่มีออเดอร์ตลาด</p>'}`;}catch(e){if(el.isConnected)el.textContent='โหลดข้อมูลไม่ได้: '+e.message}};
window.qgAdminVehicle=async(id,status,suggested)=>{if(!admin())return;const capacity=status==='active'?Number(prompt('ความจุที่ตรวจจากเอกสารรถ (กก.)',String(suggested||''))):null;if(status==='active'&&(!Number.isFinite(capacity)||capacity<=0||capacity>1000))return toast('ความจุไม่ถูกต้อง');if(!confirm(status==='active'?'ยืนยันว่าได้ตรวจรถและความจุแล้ว?':'ระงับรถคันนี้จากงานตลาด?'))return;try{await qtSupabaseRpc('market_verify_rider_vehicle',{p_rider:id,p_capacity:capacity,p_status:status});toast('บันทึกสถานะรถแล้ว');renderAdminMarket()}catch(e){toast('บันทึกไม่ได้: '+e.message)}};
})();
