/* Opt-in Web Push. No auth token is sent to or persisted by the service worker. */
(function(){
 let registrationTask=null;
 const deviceKey='qg-rider-push-device';
 function device(){let id=localStorage.getItem(deviceKey);if(!id){id=crypto.randomUUID();localStorage.setItem(deviceKey,id)}return id}
 async function api(action,body={},token){const response=await fetch(SB.URL+'/functions/v1/rider-web-push',{method:'POST',headers:{apikey:SB.KEY,Authorization:'Bearer '+(token||await getAccessToken()),'Content-Type':'application/json'},body:JSON.stringify({action,...body}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw Error(data.error||'เชื่อมต่อแจ้งเตือนไม่สำเร็จ');return data}
 function capable(){return 'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window&&isSecureContext}
 async function registration(){if(!capable())throw Error('อุปกรณ์นี้ยังไม่รองรับแจ้งเตือนเบื้องหลัง หากใช้ iPhone ให้เพิ่ม QueueGo ไปยังหน้าจอโฮมและเปิดจากไอคอน');if(!registrationTask)registrationTask=navigator.serviceWorker.register('sw.js',{scope:'./'}).then(async r=>{if(r.active)return r;await new Promise((resolve,reject)=>{const worker=r.installing||r.waiting;if(!worker)return reject(Error('กำลังติดตั้งแจ้งเตือน กรุณาลองใหม่'));const timer=setTimeout(()=>reject(Error('ติดตั้งแจ้งเตือนไม่สำเร็จ')),12000);worker.addEventListener('statechange',()=>{if(worker.state==='activated'){clearTimeout(timer);resolve()}})});return r}).catch(e=>{registrationTask=null;throw e});return registrationTask}
 async function owner(r,user){const worker=r.active||navigator.serviceWorker.controller;if(worker)worker.postMessage({type:'QUEUEGO_OWNER',userId:user||null})}
 window.qgSyncPushOwner=async function(){if(!capable()||!S.user)return;const user=S.user.id,session=S.session;try{const r=await registration();if(!riderSessionMatches(session)||S.user?.id!==user)return;await owner(r,user);if(Notification.permission!=='granted')return;const subscription=await r.pushManager.getSubscription();if(subscription){const bound=await api('subscribe',{deviceId:device(),subscription:subscription.toJSON()});if(bound.deviceId)localStorage.setItem(deviceKey,bound.deviceId);if(riderSessionMatches(session)&&S.user?.id===user)qgPushStatus('เปิดแจ้งเตือนเบื้องหลังแล้ว')}}catch(e){qgPushStatus('แจ้งเตือนยังไม่พร้อม — แตะเพื่อเชื่อมต่อใหม่')}};
 window.qgEnableRiderPush=async function(){const user=S.user?.id,session=S.session;if(!user)return;try{if(!capable())throw Error('อุปกรณ์นี้ยังไม่รองรับ หากใช้ iPhone ให้เพิ่ม QueueGo ไปยังหน้าจอโฮมก่อน');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('ยังไม่ได้อนุญาตแจ้งเตือน เปิดสิทธิ์จากการตั้งค่าเบราว์เซอร์');const r=await registration();if(!riderSessionMatches(session)||S.user?.id!==user)return;const config=await api('public-key');if(!riderSessionMatches(session)||S.user?.id!==user)return;const raw=atob(config.publicKey.replace(/-/g,'+').replace(/_/g,'/'));const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));const subscription=await r.pushManager.getSubscription()||await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});if(!riderSessionMatches(session)||S.user?.id!==user)return;const bound=await api('subscribe',{deviceId:device(),subscription:subscription.toJSON()});if(bound.deviceId)localStorage.setItem(deviceKey,bound.deviceId);if(!riderSessionMatches(session)||S.user?.id!==user)return;await owner(r,user);qgPushStatus('เปิดแจ้งเตือนเบื้องหลังแล้ว');toast('เปิดแจ้งเตือนแล้ว แม้กำลังใช้ Maps')}catch(e){toast(e.message);qgPushStatus(e.message)}};
 window.qgDisableRiderPush=function(){const token=S.session?.accessToken;try{navigator.serviceWorker?.controller?.postMessage({type:'QUEUEGO_OWNER',userId:null});registrationTask?.then(r=>owner(r,null)).catch(()=>{});const id=localStorage.getItem(deviceKey);if(token&&id)api('unsubscribe',{deviceId:id},token).catch(()=>{})}catch(e){}};
 function qgPushStatus(text){const b=document.getElementById('qg-rider-push-status');if(b)b.textContent=text}
 const original=renderProfilePanel;renderProfilePanel=function(){original();const host=document.querySelector('#panel-profile .qt-settings');if(!host||host.querySelector('#qg-rider-push'))return;const b=document.createElement('button');b.id='qg-rider-push';b.className='qt-setting';b.type='button';b.innerHTML='<span>แจ้งเตือนขณะใช้ Maps<small id="qg-rider-push-status" style="display:block;font-size:11px;color:#777">แตะเปิดแจ้งเตือนเบื้องหลัง</small></span><span>›</span>';b.onclick=()=>qgEnableRiderPush();host.insertBefore(b,host.firstChild);qgSyncPushOwner()};
 navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='QUEUEGO_REFRESH'&&S.user?.id===e.data.userId)qgRiderResume()});
})();
